### ISSUE TITLE
Some of the names in the rules can easily be false positives

### ISSUE THREAD

**Issue by ghost** [qfoxb/tf2bd-lists#1]
"John", "42", "Utopian", and "VHS" occur somewhat often in usernames. Idiot Box is probably the one that occurs the least there, but can still show up enough in names. I had a person named "ultrachad420" being flagged falsely by the detector since their name contained "42".

To a lesser extent, "A.I.", "Scott Cawthon", "Mother", and "Idiot Box" may also show up from real players.

I think redacting these names would be better rather than keeping them so as to prevent non-cheaters from being flagged. I think the schema may also allow for forcing the names to have to be exact, but even then, names such as "John" or "Scott Cawthon" should be redacted regardless.

**Comment by qfoxb** [comment]
I've changed the username filter to be exact, which means that it'll only catch people with the exact name in the list to prevent this. I plan on removing the "John" filter once those bots disappear because yes, it could totally cause issues at some point. Regarding the other usernames, i've never seen anyone use those usernames that isn't a bot and the exact-username filter should fix it. Let me know if this fixes the issue

**Comment by ghost** [comment]
I think it'll fix the issue. Fair call on the "John" filter. Thanks for the fix!

**Comment by qfoxb** [comment]
Removed John as of [54f36e1](https://github.com/qfoxb/tf2bd-lists/commit/54f36e18745510d2af9f0a141fd9b76d5f320bde)
